### ISSUE TITLE
Sandpack could not resolve some modules

### ISSUE THREAD

**Issue by jeetiss** [codesandbox/nodebox-runtime#3]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

I run sandpack with `@react-pdf/renderer` library and get those errors:

```
main.js:1561 Uncaught (in promise) Error: Build failed with 6 errors:
node_modules/.store/@react-pdf/fns@2.0.0/node_modules/@react-pdf/fns/lib/index.es.js:1:30: ERROR: Could not resolve "@babel/runtime/helpers/asyncToGenerator"
node_modules/.store/@react-pdf/fns@2.0.0/node_modules/@react-pdf/fns/lib/index.es.js:2:32: ERROR: Could not resolve "@babel/runtime/regenerator"
node_modules/.store/@react-pdf/pdfkit@3.0.1/node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js:3:23: ERROR: Could not resolve "pako/lib/zlib/zstream"
node_modules/.store/@react-pdf/pdfkit@3.0.1/node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js:4:23: ERROR: Could not resolve "pako/lib/zlib/deflate.js"
node_modules/.store/@react-pdf/pdfkit@3.0.1/node_modules/@react-pdf/pdfkit/lib/pdfkit.browser.es.js:5:23: ERROR: Could not resolve "pako/lib/zlib/inflate.js"
...
```

## Link to sandbox: 

[sandbox](https://codesandbox.io/p/sandbox/sandpack-modules-not-found-mgj43p)

## Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-react version  |    2.0.1     |

**Comment by kettanaito** [comment]
Hey, @jeetiss. Thanks for reporting this. 

It looks like an issue in our dependency resolution algorithm. I will take a look and update you in this thread.

**Comment by jeetiss** [comment]
Hello, @kettanaito

I have updates on this issue: 

- `@react-pdf/fns` has unspecified dependency `@babel/runtime` that causes errors in sandbox and i already fixed it:
- https://github.com/diegomura/react-pdf/pull/2215

- `pako` is deduped when react-pdf is installed via sandbox but should not and this is the reason and i can't fix that

```bash
react-pdf % yarn list --pattern pako
yarn list v1.22.17
├─ pako@1.0.11
└─ unicode-trie@2.0.0
   └─ pako@0.2.9
✨  Done in 0.33s.
```

Hope this helps

**Comment by kettanaito** [comment]
Thanks for the follow up!

Please, can you still reproduce the dependency issue? I can't, following your sandbox. This is the preview I get:

<img width="874" alt="Screenshot 2023-03-07 at 12 36 33" src="https://user-images.githubusercontent.com/14984911/223411260-466520f9-ce0d-4153-b5cc-a5475a189218.png">

This appears to be correct. There are also no errors in the console. 

The CodeSandbox editor doesn't display the preview likely due to the generated PDF being an external resource blocked by the `Content-Security-Policy` (you can see the "blocked by Chrome" message in the errored `iframe`). We can certainly improve on that but the dependency issue doesn't seem to be the case anymore. 

Please let me know if I'm missing something.

**Comment by jeetiss** [comment]
Yep, it works now! thanks
